import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          font-sans
          antialiased
          bg-gray-950
          text-gray-50
          flex
          justify-center
          items-center
          min-h-screen
        `}
      >
        {children}
      </body>
    </html>
  );
}
